export interface Recipe {
  id: string;
  title: string;
  description: string;
  cuisine: string;
  difficulty: "Easy" | "Intermediate" | "Advanced";
  prepTime: string;
  cookTime: string;
  servings: number;
  emoji: string;
  ingredients: string[];
  instructions: string[];
  tags: string[];
}

export const recipes: Recipe[] = [
  {
    id: "truffle-mushroom-risotto",
    title: "Truffle Mushroom Risotto",
    description:
      "A luxurious Italian risotto with mixed wild mushrooms and a drizzle of truffle oil for an unforgettable umami experience.",
    cuisine: "Italian",
    difficulty: "Intermediate",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    emoji: "🍄",
    ingredients: [
      "1½ cups Arborio rice",
      "8 oz mixed wild mushrooms, sliced",
      "4 cups warm vegetable broth",
      "½ cup dry white wine",
      "1 small onion, finely diced",
      "2 cloves garlic, minced",
      "½ cup grated Parmesan cheese",
      "2 tbsp butter",
      "1 tbsp truffle oil",
      "2 tbsp olive oil",
      "Fresh thyme sprigs",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Heat olive oil in a large skillet over medium-high heat. Sauté mushrooms until golden brown, about 5-7 minutes. Season with salt, pepper, and thyme. Set aside.",
      "In a heavy-bottomed pot, melt 1 tbsp butter over medium heat. Sauté onion until translucent, about 3 minutes. Add garlic and cook 1 minute more.",
      "Add Arborio rice and stir for 2 minutes until the edges become translucent.",
      "Pour in white wine and stir until fully absorbed.",
      "Add warm broth one ladle at a time, stirring frequently. Wait until each addition is absorbed before adding the next. This process takes about 18-20 minutes.",
      "When rice is creamy and al dente, remove from heat. Stir in Parmesan, remaining butter, and sautéed mushrooms.",
      "Plate and drizzle with truffle oil. Garnish with fresh thyme and extra Parmesan.",
    ],
    tags: ["vegetarian", "comfort food", "dinner", "mushrooms"],
  },
  {
    id: "miso-glazed-salmon",
    title: "Miso Glazed Salmon",
    description:
      "Flaky salmon fillets coated in a sweet and savory white miso glaze, broiled to caramelized perfection.",
    cuisine: "Japanese",
    difficulty: "Easy",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    emoji: "🐟",
    ingredients: [
      "4 salmon fillets (6 oz each)",
      "3 tbsp white miso paste",
      "2 tbsp mirin",
      "1 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "1 tbsp brown sugar",
      "1 tsp sesame oil",
      "Sesame seeds for garnish",
      "Sliced green onions for garnish",
    ],
    instructions: [
      "Whisk together miso paste, mirin, soy sauce, rice vinegar, brown sugar, and sesame oil in a bowl.",
      "Place salmon fillets in a baking dish and coat generously with the miso glaze. Marinate for at least 30 minutes (or overnight for best results).",
      "Preheat broiler to high. Line a baking sheet with foil.",
      "Place salmon on the prepared baking sheet. Broil for 8-10 minutes until the glaze is caramelized and salmon flakes easily.",
      "Garnish with sesame seeds and sliced green onions. Serve with steamed rice and vegetables.",
    ],
    tags: ["seafood", "high-protein", "dinner", "quick"],
  },
  {
    id: "thai-green-curry",
    title: "Thai Green Curry",
    description:
      "A fragrant and creamy coconut curry with tender vegetables, Thai basil, and your choice of protein.",
    cuisine: "Thai",
    difficulty: "Easy",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: 4,
    emoji: "🍛",
    ingredients: [
      "2 tbsp green curry paste",
      "1 can (14 oz) coconut milk",
      "1 lb chicken breast or tofu, cubed",
      "1 cup bamboo shoots",
      "1 red bell pepper, sliced",
      "1 cup Thai eggplant or regular eggplant, diced",
      "1 cup green beans, trimmed",
      "2 tbsp fish sauce (or soy sauce for vegetarian)",
      "1 tbsp palm sugar or brown sugar",
      "Fresh Thai basil leaves",
      "2 kaffir lime leaves",
      "1 Thai chili, sliced (optional)",
      "Jasmine rice for serving",
    ],
    instructions: [
      "Scoop the thick cream from the top of the coconut can into a wok or deep pan over medium-high heat.",
      "Add green curry paste and fry for 2 minutes until fragrant and the oil separates.",
      "Add chicken or tofu and cook for 3-4 minutes until lightly browned.",
      "Pour in remaining coconut milk, bamboo shoots, eggplant, and kaffir lime leaves. Simmer for 10 minutes.",
      "Add bell pepper, green beans, fish sauce, and sugar. Cook for 5 more minutes until vegetables are tender-crisp.",
      "Remove from heat, stir in Thai basil. Serve over jasmine rice with sliced chili on top.",
    ],
    tags: ["spicy", "curry", "dinner", "gluten-free"],
  },
  {
    id: "classic-french-crepes",
    title: "Classic French Crêpes",
    description:
      "Thin, delicate crêpes that can be filled with Nutella, fresh berries, whipped cream, or savory fillings.",
    cuisine: "French",
    difficulty: "Easy",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 8,
    emoji: "🥞",
    ingredients: [
      "1 cup all-purpose flour",
      "2 large eggs",
      "1¼ cups whole milk",
      "2 tbsp melted butter, plus more for the pan",
      "1 tbsp sugar (for sweet crêpes)",
      "¼ tsp salt",
      "1 tsp vanilla extract",
    ],
    instructions: [
      "Combine flour, eggs, milk, melted butter, sugar, salt, and vanilla in a blender. Blend until smooth. Alternatively, whisk in a bowl until no lumps remain.",
      "Let the batter rest in the refrigerator for at least 30 minutes (this helps the crêpes stay tender).",
      "Heat an 8-inch non-stick skillet or crêpe pan over medium heat. Brush with a thin layer of butter.",
      "Pour about 3 tablespoons of batter into the center of the pan. Immediately tilt and rotate the pan to spread the batter into a thin, even circle.",
      "Cook for about 1-2 minutes until the edges start to brown and lift from the pan. Flip carefully and cook for another 30 seconds.",
      "Stack finished crêpes on a plate. Fill with your choice of toppings: Nutella and bananas, fresh berries with whipped cream, or ham and cheese for savory.",
    ],
    tags: ["breakfast", "dessert", "french", "versatile"],
  },
  {
    id: "chicken-tikka-masala",
    title: "Chicken Tikka Masala",
    description:
      "Tender marinated chicken in a rich, creamy tomato sauce with aromatic Indian spices. A crowd-pleasing classic.",
    cuisine: "Indian",
    difficulty: "Intermediate",
    prepTime: "30 min",
    cookTime: "40 min",
    servings: 6,
    emoji: "🍗",
    ingredients: [
      "2 lbs boneless chicken thighs, cubed",
      "1 cup plain yogurt",
      "2 tbsp lemon juice",
      "2 tsp garam masala",
      "1 tsp turmeric",
      "1 tsp cumin",
      "1 tsp paprika",
      "1 can (14 oz) crushed tomatoes",
      "1 cup heavy cream",
      "1 large onion, diced",
      "4 cloves garlic, minced",
      "1 inch fresh ginger, grated",
      "2 tbsp butter",
      "2 tbsp vegetable oil",
      "Fresh cilantro for garnish",
      "Naan bread and basmati rice for serving",
    ],
    instructions: [
      "Mix yogurt, lemon juice, half the garam masala, turmeric, cumin, and paprika. Add chicken and marinate for at least 2 hours.",
      "Preheat oven to 450°F. Thread chicken onto skewers or spread on a baking sheet. Bake for 15 minutes until lightly charred.",
      "Heat oil and butter in a large skillet over medium heat. Sauté onion until golden, about 8 minutes.",
      "Add garlic and ginger, cook 2 minutes. Add remaining garam masala and paprika, stir for 1 minute.",
      "Pour in crushed tomatoes and simmer for 15 minutes, stirring occasionally.",
      "Stir in heavy cream and baked chicken pieces. Simmer for 10 minutes until sauce thickens.",
      "Garnish with fresh cilantro. Serve with warm naan bread and basmati rice.",
    ],
    tags: ["indian", "spicy", "dinner", "comfort food"],
  },
  {
    id: "avocado-poke-bowl",
    title: "Avocado Poké Bowl",
    description:
      "A vibrant and healthy bowl with fresh sushi-grade tuna, creamy avocado, edamame, and a sesame soy dressing.",
    cuisine: "Hawaiian",
    difficulty: "Easy",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: 2,
    emoji: "🥑",
    ingredients: [
      "8 oz sushi-grade ahi tuna, cubed",
      "1 ripe avocado, sliced",
      "1 cup cooked sushi rice",
      "½ cup shelled edamame",
      "½ cup cucumber, diced",
      "¼ cup pickled ginger",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "1 tsp rice vinegar",
      "Sesame seeds",
      "Sliced nori strips",
      "Sriracha mayo (optional)",
    ],
    instructions: [
      "Cook sushi rice according to package directions. Season with rice vinegar and let cool slightly.",
      "In a small bowl, whisk together soy sauce, sesame oil, and rice vinegar for the dressing.",
      "Toss cubed tuna with half the dressing and let sit for 5 minutes.",
      "Divide rice between two bowls. Arrange tuna, avocado, edamame, cucumber, and pickled ginger in sections on top.",
      "Drizzle with remaining dressing. Sprinkle with sesame seeds and nori strips. Add sriracha mayo if desired.",
    ],
    tags: ["healthy", "seafood", "bowl", "quick", "lunch"],
  },
  {
    id: "sourdough-bread",
    title: "Artisan Sourdough Bread",
    description:
      "A crusty, tangy loaf with an open crumb structure. The ultimate bread-baking achievement using a sourdough starter.",
    cuisine: "Artisan",
    difficulty: "Advanced",
    prepTime: "30 min",
    cookTime: "45 min",
    servings: 1,
    emoji: "🍞",
    ingredients: [
      "500g bread flour",
      "350g warm water",
      "100g active sourdough starter",
      "10g salt",
    ],
    instructions: [
      "Mix flour and water in a large bowl. Let it rest (autolyse) for 30 minutes.",
      "Add sourdough starter and salt. Mix until well incorporated using the pinch-and-fold method.",
      "Perform 4 sets of stretch and folds, 30 minutes apart, over 2 hours.",
      "Let the dough bulk ferment at room temperature for 4-6 hours (or until doubled in size). Alternatively, cold ferment in the fridge for 12-18 hours.",
      "Shape the dough on a lightly floured surface. Place seam-side up in a floured banneton basket. Cover and refrigerate overnight.",
      "Preheat oven to 500°F with a Dutch oven inside for at least 45 minutes.",
      "Score the top of the dough with a sharp blade. Carefully place in the hot Dutch oven. Bake covered for 20 minutes, then uncover and bake at 450°F for 20-25 more minutes until deep golden brown.",
      "Cool on a wire rack for at least 1 hour before slicing.",
    ],
    tags: ["bread", "baking", "artisan", "sourdough", "advanced"],
  },
  {
    id: "tacos-al-pastor",
    title: "Tacos al Pastor",
    description:
      "Tender marinated pork with sweet pineapple, onion, and cilantro on warm corn tortillas. A Mexican street food classic.",
    cuisine: "Mexican",
    difficulty: "Intermediate",
    prepTime: "20 min",
    cookTime: "25 min",
    servings: 6,
    emoji: "🌮",
    ingredients: [
      "2 lbs pork shoulder, thinly sliced",
      "3 dried guajillo chiles, stemmed and seeded",
      "2 chipotle peppers in adobo",
      "½ cup pineapple juice",
      "3 cloves garlic",
      "1 tsp cumin",
      "1 tsp oregano",
      "½ tsp achiote paste (optional)",
      "1 cup fresh pineapple, diced",
      "12 small corn tortillas",
      "Fresh cilantro, diced onion, lime wedges",
      "Salsa verde for serving",
    ],
    instructions: [
      "Rehydrate guajillo chiles in hot water for 15 minutes. Drain.",
      "Blend chiles, chipotle peppers, pineapple juice, garlic, cumin, oregano, and achiote paste until smooth.",
      "Marinate pork slices in the sauce for at least 2 hours (overnight is best).",
      "Heat a cast iron skillet or grill over high heat. Cook pork in batches, getting a nice char on each side, about 3-4 minutes per side.",
      "In the same pan, quickly sear pineapple chunks until caramelized.",
      "Warm tortillas on the skillet. Chop pork into small pieces and load onto tortillas with pineapple, onion, cilantro, and a squeeze of lime. Serve with salsa verde.",
    ],
    tags: ["mexican", "street food", "dinner", "spicy"],
  },
  {
    id: "matcha-tiramisu",
    title: "Matcha Tiramisu",
    description:
      "A Japanese-Italian fusion dessert featuring layers of matcha-soaked ladyfingers and mascarpone cream.",
    cuisine: "Fusion",
    difficulty: "Intermediate",
    prepTime: "30 min",
    cookTime: "0 min",
    servings: 8,
    emoji: "🍵",
    ingredients: [
      "24 ladyfinger cookies",
      "16 oz mascarpone cheese, room temperature",
      "1 cup heavy whipping cream",
      "½ cup sugar",
      "3 egg yolks",
      "2 tbsp ceremonial grade matcha powder",
      "1 cup warm water",
      "2 tbsp white chocolate, melted (optional)",
      "Extra matcha for dusting",
    ],
    instructions: [
      "Dissolve 2 tbsp matcha in warm water, whisking until smooth. Let cool to room temperature.",
      "Beat egg yolks and sugar until thick and pale yellow, about 3 minutes.",
      "Add mascarpone to egg mixture and beat until smooth and creamy.",
      "In a separate bowl, whip heavy cream to stiff peaks. Gently fold into the mascarpone mixture.",
      "Quickly dip each ladyfinger in the matcha liquid (don't soak—just a quick dip). Layer in a 9x13 dish.",
      "Spread half the mascarpone cream over the ladyfingers. Repeat with another layer.",
      "Cover and refrigerate for at least 6 hours, preferably overnight.",
      "Before serving, dust generously with matcha powder and drizzle with melted white chocolate if desired.",
    ],
    tags: ["dessert", "fusion", "no-bake", "matcha"],
  },
];

export const cuisines = [
  "All",
  "Italian",
  "Japanese",
  "Thai",
  "French",
  "Indian",
  "Hawaiian",
  "Artisan",
  "Mexican",
  "Fusion",
];

export const difficulties = ["All", "Easy", "Intermediate", "Advanced"];
